name: Example workflow using secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub secret with spaces
        run: echo "My secret is $(echo $SECRET | sed 's/./& /g')"
        env:
          SECRET: ${{ secrets.MY_SECRET }}